version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=nodedb
      - MYSQL_DATABASE=database
    ports:
      - "3000:3000"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: nodedb
      MYSQL_DATABASE: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: